// Copyright (c) the go-webengine/browserproxy authors.
// SPDX-License-Identifier: BSD-3-Clause

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: proto/browser.proto

package browserpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Browser_Session_FullMethodName = "/browserproxy.v1.Browser/Session"
)

// BrowserClient is the client API for Browser service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Browser is the remote-browser service. A single long-lived bidirectional
// stream models one browser tab: the client sends input events, the server
// streams back rendered frames and chrome state. This maps the browser's
// natural full-duplex interaction directly onto gRPC streaming — the transport
// underneath is grpc-transports/websocket, so the same client compiles to
// GOOS=js/wasm and runs in the browser with no sidecar proxy.
type BrowserClient interface {
	// Session drives one tab for the lifetime of the stream.
	Session(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientMsg, ServerMsg], error)
}

type browserClient struct {
	cc grpc.ClientConnInterface
}

func NewBrowserClient(cc grpc.ClientConnInterface) BrowserClient {
	return &browserClient{cc}
}

func (c *browserClient) Session(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientMsg, ServerMsg], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Browser_ServiceDesc.Streams[0], Browser_Session_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ClientMsg, ServerMsg]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Browser_SessionClient = grpc.BidiStreamingClient[ClientMsg, ServerMsg]

// BrowserServer is the server API for Browser service.
// All implementations must embed UnimplementedBrowserServer
// for forward compatibility.
//
// Browser is the remote-browser service. A single long-lived bidirectional
// stream models one browser tab: the client sends input events, the server
// streams back rendered frames and chrome state. This maps the browser's
// natural full-duplex interaction directly onto gRPC streaming — the transport
// underneath is grpc-transports/websocket, so the same client compiles to
// GOOS=js/wasm and runs in the browser with no sidecar proxy.
type BrowserServer interface {
	// Session drives one tab for the lifetime of the stream.
	Session(grpc.BidiStreamingServer[ClientMsg, ServerMsg]) error
	mustEmbedUnimplementedBrowserServer()
}

// UnimplementedBrowserServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBrowserServer struct{}

func (UnimplementedBrowserServer) Session(grpc.BidiStreamingServer[ClientMsg, ServerMsg]) error {
	return status.Error(codes.Unimplemented, "method Session not implemented")
}
func (UnimplementedBrowserServer) mustEmbedUnimplementedBrowserServer() {}
func (UnimplementedBrowserServer) testEmbeddedByValue()                 {}

// UnsafeBrowserServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BrowserServer will
// result in compilation errors.
type UnsafeBrowserServer interface {
	mustEmbedUnimplementedBrowserServer()
}

func RegisterBrowserServer(s grpc.ServiceRegistrar, srv BrowserServer) {
	// If the following call panics, it indicates UnimplementedBrowserServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Browser_ServiceDesc, srv)
}

func _Browser_Session_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BrowserServer).Session(&grpc.GenericServerStream[ClientMsg, ServerMsg]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Browser_SessionServer = grpc.BidiStreamingServer[ClientMsg, ServerMsg]

// Browser_ServiceDesc is the grpc.ServiceDesc for Browser service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Browser_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "browserproxy.v1.Browser",
	HandlerType: (*BrowserServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Session",
			Handler:       _Browser_Session_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/browser.proto",
}
