// Copyright (c) the go-webengine/browserproxy authors.
// SPDX-License-Identifier: BSD-3-Clause

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/browser.proto

package browserpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ClientMsg is one input event from the client. Exactly one field is set.
type ClientMsg struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*ClientMsg_Navigate
	//	*ClientMsg_Click
	//	*ClientMsg_Scroll
	//	*ClientMsg_Key
	//	*ClientMsg_Resize
	//	*ClientMsg_Back
	//	*ClientMsg_Forward
	Msg           isClientMsg_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientMsg) Reset() {
	*x = ClientMsg{}
	mi := &file_proto_browser_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMsg) ProtoMessage() {}

func (x *ClientMsg) ProtoReflect() protoreflect.Message {
	mi := &file_proto_browser_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMsg.ProtoReflect.Descriptor instead.
func (*ClientMsg) Descriptor() ([]byte, []int) {
	return file_proto_browser_proto_rawDescGZIP(), []int{0}
}

func (x *ClientMsg) GetMsg() isClientMsg_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *ClientMsg) GetNavigate() *Navigate {
	if x != nil {
		if x, ok := x.Msg.(*ClientMsg_Navigate); ok {
			return x.Navigate
		}
	}
	return nil
}

func (x *ClientMsg) GetClick() *Click {
	if x != nil {
		if x, ok := x.Msg.(*ClientMsg_Click); ok {
			return x.Click
		}
	}
	return nil
}

func (x *ClientMsg) GetScroll() *Scroll {
	if x != nil {
		if x, ok := x.Msg.(*ClientMsg_Scroll); ok {
			return x.Scroll
		}
	}
	return nil
}

func (x *ClientMsg) GetKey() *Key {
	if x != nil {
		if x, ok := x.Msg.(*ClientMsg_Key); ok {
			return x.Key
		}
	}
	return nil
}

func (x *ClientMsg) GetResize() *Resize {
	if x != nil {
		if x, ok := x.Msg.(*ClientMsg_Resize); ok {
			return x.Resize
		}
	}
	return nil
}

func (x *ClientMsg) GetBack() *Back {
	if x != nil {
		if x, ok := x.Msg.(*ClientMsg_Back); ok {
			return x.Back
		}
	}
	return nil
}

func (x *ClientMsg) GetForward() *Forward {
	if x != nil {
		if x, ok := x.Msg.(*ClientMsg_Forward); ok {
			return x.Forward
		}
	}
	return nil
}

type isClientMsg_Msg interface {
	isClientMsg_Msg()
}

type ClientMsg_Navigate struct {
	Navigate *Navigate `protobuf:"bytes,1,opt,name=navigate,proto3,oneof"`
}

type ClientMsg_Click struct {
	Click *Click `protobuf:"bytes,2,opt,name=click,proto3,oneof"`
}

type ClientMsg_Scroll struct {
	Scroll *Scroll `protobuf:"bytes,3,opt,name=scroll,proto3,oneof"`
}

type ClientMsg_Key struct {
	Key *Key `protobuf:"bytes,4,opt,name=key,proto3,oneof"`
}

type ClientMsg_Resize struct {
	Resize *Resize `protobuf:"bytes,5,opt,name=resize,proto3,oneof"`
}

type ClientMsg_Back struct {
	Back *Back `protobuf:"bytes,6,opt,name=back,proto3,oneof"`
}

type ClientMsg_Forward struct {
	Forward *Forward `protobuf:"bytes,7,opt,name=forward,proto3,oneof"`
}

func (*ClientMsg_Navigate) isClientMsg_Msg() {}

func (*ClientMsg_Click) isClientMsg_Msg() {}

func (*ClientMsg_Scroll) isClientMsg_Msg() {}

func (*ClientMsg_Key) isClientMsg_Msg() {}

func (*ClientMsg_Resize) isClientMsg_Msg() {}

func (*ClientMsg_Back) isClientMsg_Msg() {}

func (*ClientMsg_Forward) isClientMsg_Msg() {}

// Navigate loads a new URL as a fresh history entry.
type Navigate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Navigate) Reset() {
	*x = Navigate{}
	mi := &file_proto_browser_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Navigate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Navigate) ProtoMessage() {}

func (x *Navigate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_browser_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Navigate.ProtoReflect.Descriptor instead.
func (*Navigate) Descriptor() ([]byte, []int) {
	return file_proto_browser_proto_rawDescGZIP(), []int{1}
}

func (x *Navigate) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

// Click reports a content-area click in viewport pixel coordinates.
type Click struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Click) Reset() {
	*x = Click{}
	mi := &file_proto_browser_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Click) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Click) ProtoMessage() {}

func (x *Click) ProtoReflect() protoreflect.Message {
	mi := &file_proto_browser_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Click.ProtoReflect.Descriptor instead.
func (*Click) Descriptor() ([]byte, []int) {
	return file_proto_browser_proto_rawDescGZIP(), []int{2}
}

func (x *Click) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Click) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

// Scroll adjusts the vertical scroll by dy pixels (positive = down).
type Scroll struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dy            int32                  `protobuf:"varint,1,opt,name=dy,proto3" json:"dy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Scroll) Reset() {
	*x = Scroll{}
	mi := &file_proto_browser_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Scroll) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Scroll) ProtoMessage() {}

func (x *Scroll) ProtoReflect() protoreflect.Message {
	mi := &file_proto_browser_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Scroll.ProtoReflect.Descriptor instead.
func (*Scroll) Descriptor() ([]byte, []int) {
	return file_proto_browser_proto_rawDescGZIP(), []int{3}
}

func (x *Scroll) GetDy() int32 {
	if x != nil {
		return x.Dy
	}
	return 0
}

// Key reports a key press by name (e.g. "Enter", "ArrowDown").
type Key struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Key) Reset() {
	*x = Key{}
	mi := &file_proto_browser_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Key) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Key) ProtoMessage() {}

func (x *Key) ProtoReflect() protoreflect.Message {
	mi := &file_proto_browser_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Key.ProtoReflect.Descriptor instead.
func (*Key) Descriptor() ([]byte, []int) {
	return file_proto_browser_proto_rawDescGZIP(), []int{4}
}

func (x *Key) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

// Resize sets a new content-area viewport size in pixels.
type Resize struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	W             int32                  `protobuf:"varint,1,opt,name=w,proto3" json:"w,omitempty"`
	H             int32                  `protobuf:"varint,2,opt,name=h,proto3" json:"h,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resize) Reset() {
	*x = Resize{}
	mi := &file_proto_browser_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resize) ProtoMessage() {}

func (x *Resize) ProtoReflect() protoreflect.Message {
	mi := &file_proto_browser_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resize.ProtoReflect.Descriptor instead.
func (*Resize) Descriptor() ([]byte, []int) {
	return file_proto_browser_proto_rawDescGZIP(), []int{5}
}

func (x *Resize) GetW() int32 {
	if x != nil {
		return x.W
	}
	return 0
}

func (x *Resize) GetH() int32 {
	if x != nil {
		return x.H
	}
	return 0
}

// Back re-loads the most recent back-history entry.
type Back struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Back) Reset() {
	*x = Back{}
	mi := &file_proto_browser_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Back) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Back) ProtoMessage() {}

func (x *Back) ProtoReflect() protoreflect.Message {
	mi := &file_proto_browser_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Back.ProtoReflect.Descriptor instead.
func (*Back) Descriptor() ([]byte, []int) {
	return file_proto_browser_proto_rawDescGZIP(), []int{6}
}

// Forward re-loads the next forward-history entry.
type Forward struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Forward) Reset() {
	*x = Forward{}
	mi := &file_proto_browser_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Forward) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Forward) ProtoMessage() {}

func (x *Forward) ProtoReflect() protoreflect.Message {
	mi := &file_proto_browser_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Forward.ProtoReflect.Descriptor instead.
func (*Forward) Descriptor() ([]byte, []int) {
	return file_proto_browser_proto_rawDescGZIP(), []int{7}
}

// ServerMsg is one message streamed to the client. Exactly one field is set.
type ServerMsg struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*ServerMsg_Frame
	//	*ServerMsg_State
	//	*ServerMsg_Error
	Msg           isServerMsg_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMsg) Reset() {
	*x = ServerMsg{}
	mi := &file_proto_browser_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMsg) ProtoMessage() {}

func (x *ServerMsg) ProtoReflect() protoreflect.Message {
	mi := &file_proto_browser_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMsg.ProtoReflect.Descriptor instead.
func (*ServerMsg) Descriptor() ([]byte, []int) {
	return file_proto_browser_proto_rawDescGZIP(), []int{8}
}

func (x *ServerMsg) GetMsg() isServerMsg_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *ServerMsg) GetFrame() *Frame {
	if x != nil {
		if x, ok := x.Msg.(*ServerMsg_Frame); ok {
			return x.Frame
		}
	}
	return nil
}

func (x *ServerMsg) GetState() *State {
	if x != nil {
		if x, ok := x.Msg.(*ServerMsg_State); ok {
			return x.State
		}
	}
	return nil
}

func (x *ServerMsg) GetError() *Error {
	if x != nil {
		if x, ok := x.Msg.(*ServerMsg_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isServerMsg_Msg interface {
	isServerMsg_Msg()
}

type ServerMsg_Frame struct {
	Frame *Frame `protobuf:"bytes,1,opt,name=frame,proto3,oneof"`
}

type ServerMsg_State struct {
	State *State `protobuf:"bytes,2,opt,name=state,proto3,oneof"`
}

type ServerMsg_Error struct {
	Error *Error `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}

func (*ServerMsg_Frame) isServerMsg_Msg() {}

func (*ServerMsg_State) isServerMsg_Msg() {}

func (*ServerMsg_Error) isServerMsg_Msg() {}

// Frame is a rendered viewport slice: raw PNG bytes (no base64 — gRPC carries
// binary natively) taken from the full page at vertical scroll offset_y.
type Frame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Png           []byte                 `protobuf:"bytes,1,opt,name=png,proto3" json:"png,omitempty"`
	W             int32                  `protobuf:"varint,2,opt,name=w,proto3" json:"w,omitempty"`
	H             int32                  `protobuf:"varint,3,opt,name=h,proto3" json:"h,omitempty"`
	OffsetY       int32                  `protobuf:"varint,4,opt,name=offset_y,json=offsetY,proto3" json:"offset_y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Frame) Reset() {
	*x = Frame{}
	mi := &file_proto_browser_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Frame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Frame) ProtoMessage() {}

func (x *Frame) ProtoReflect() protoreflect.Message {
	mi := &file_proto_browser_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Frame.ProtoReflect.Descriptor instead.
func (*Frame) Descriptor() ([]byte, []int) {
	return file_proto_browser_proto_rawDescGZIP(), []int{9}
}

func (x *Frame) GetPng() []byte {
	if x != nil {
		return x.Png
	}
	return nil
}

func (x *Frame) GetW() int32 {
	if x != nil {
		return x.W
	}
	return 0
}

func (x *Frame) GetH() int32 {
	if x != nil {
		return x.H
	}
	return 0
}

func (x *Frame) GetOffsetY() int32 {
	if x != nil {
		return x.OffsetY
	}
	return 0
}

// State is the browser-chrome model: what the address bar and the
// back/forward buttons should show.
type State struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Loading       bool                   `protobuf:"varint,3,opt,name=loading,proto3" json:"loading,omitempty"`
	CanBack       bool                   `protobuf:"varint,4,opt,name=can_back,json=canBack,proto3" json:"can_back,omitempty"`
	CanForward    bool                   `protobuf:"varint,5,opt,name=can_forward,json=canForward,proto3" json:"can_forward,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *State) Reset() {
	*x = State{}
	mi := &file_proto_browser_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *State) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*State) ProtoMessage() {}

func (x *State) ProtoReflect() protoreflect.Message {
	mi := &file_proto_browser_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use State.ProtoReflect.Descriptor instead.
func (*State) Descriptor() ([]byte, []int) {
	return file_proto_browser_proto_rawDescGZIP(), []int{10}
}

func (x *State) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *State) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *State) GetLoading() bool {
	if x != nil {
		return x.Loading
	}
	return false
}

func (x *State) GetCanBack() bool {
	if x != nil {
		return x.CanBack
	}
	return false
}

func (x *State) GetCanForward() bool {
	if x != nil {
		return x.CanForward
	}
	return false
}

// Error reports a navigation or protocol failure the client should surface
// (e.g. an SSRF-blocked URL or an unreachable host).
type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_proto_browser_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_proto_browser_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_proto_browser_proto_rawDescGZIP(), []int{11}
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_browser_proto protoreflect.FileDescriptor

const file_proto_browser_proto_rawDesc = "" +
	"\n" +
	"\x13proto/browser.proto\x12\x0fbrowserproxy.v1\"\xee\x02\n" +
	"\tClientMsg\x127\n" +
	"\bnavigate\x18\x01 \x01(\v2\x19.browserproxy.v1.NavigateH\x00R\bnavigate\x12.\n" +
	"\x05click\x18\x02 \x01(\v2\x16.browserproxy.v1.ClickH\x00R\x05click\x121\n" +
	"\x06scroll\x18\x03 \x01(\v2\x17.browserproxy.v1.ScrollH\x00R\x06scroll\x12(\n" +
	"\x03key\x18\x04 \x01(\v2\x14.browserproxy.v1.KeyH\x00R\x03key\x121\n" +
	"\x06resize\x18\x05 \x01(\v2\x17.browserproxy.v1.ResizeH\x00R\x06resize\x12+\n" +
	"\x04back\x18\x06 \x01(\v2\x15.browserproxy.v1.BackH\x00R\x04back\x124\n" +
	"\aforward\x18\a \x01(\v2\x18.browserproxy.v1.ForwardH\x00R\aforwardB\x05\n" +
	"\x03msg\"\x1c\n" +
	"\bNavigate\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"#\n" +
	"\x05Click\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\"\x18\n" +
	"\x06Scroll\x12\x0e\n" +
	"\x02dy\x18\x01 \x01(\x05R\x02dy\"\x17\n" +
	"\x03Key\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"$\n" +
	"\x06Resize\x12\f\n" +
	"\x01w\x18\x01 \x01(\x05R\x01w\x12\f\n" +
	"\x01h\x18\x02 \x01(\x05R\x01h\"\x06\n" +
	"\x04Back\"\t\n" +
	"\aForward\"\xa2\x01\n" +
	"\tServerMsg\x12.\n" +
	"\x05frame\x18\x01 \x01(\v2\x16.browserproxy.v1.FrameH\x00R\x05frame\x12.\n" +
	"\x05state\x18\x02 \x01(\v2\x16.browserproxy.v1.StateH\x00R\x05state\x12.\n" +
	"\x05error\x18\x03 \x01(\v2\x16.browserproxy.v1.ErrorH\x00R\x05errorB\x05\n" +
	"\x03msg\"P\n" +
	"\x05Frame\x12\x10\n" +
	"\x03png\x18\x01 \x01(\fR\x03png\x12\f\n" +
	"\x01w\x18\x02 \x01(\x05R\x01w\x12\f\n" +
	"\x01h\x18\x03 \x01(\x05R\x01h\x12\x19\n" +
	"\boffset_y\x18\x04 \x01(\x05R\aoffsetY\"\x85\x01\n" +
	"\x05State\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\aloading\x18\x03 \x01(\bR\aloading\x12\x19\n" +
	"\bcan_back\x18\x04 \x01(\bR\acanBack\x12\x1f\n" +
	"\vcan_forward\x18\x05 \x01(\bR\n" +
	"canForward\"!\n" +
	"\x05Error\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2P\n" +
	"\aBrowser\x12E\n" +
	"\aSession\x12\x1a.browserproxy.v1.ClientMsg\x1a\x1a.browserproxy.v1.ServerMsg(\x010\x01B0Z.github.com/go-webengine/browserproxy/browserpbb\x06proto3"

var (
	file_proto_browser_proto_rawDescOnce sync.Once
	file_proto_browser_proto_rawDescData []byte
)

func file_proto_browser_proto_rawDescGZIP() []byte {
	file_proto_browser_proto_rawDescOnce.Do(func() {
		file_proto_browser_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_browser_proto_rawDesc), len(file_proto_browser_proto_rawDesc)))
	})
	return file_proto_browser_proto_rawDescData
}

var file_proto_browser_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_browser_proto_goTypes = []any{
	(*ClientMsg)(nil), // 0: browserproxy.v1.ClientMsg
	(*Navigate)(nil),  // 1: browserproxy.v1.Navigate
	(*Click)(nil),     // 2: browserproxy.v1.Click
	(*Scroll)(nil),    // 3: browserproxy.v1.Scroll
	(*Key)(nil),       // 4: browserproxy.v1.Key
	(*Resize)(nil),    // 5: browserproxy.v1.Resize
	(*Back)(nil),      // 6: browserproxy.v1.Back
	(*Forward)(nil),   // 7: browserproxy.v1.Forward
	(*ServerMsg)(nil), // 8: browserproxy.v1.ServerMsg
	(*Frame)(nil),     // 9: browserproxy.v1.Frame
	(*State)(nil),     // 10: browserproxy.v1.State
	(*Error)(nil),     // 11: browserproxy.v1.Error
}
var file_proto_browser_proto_depIdxs = []int32{
	1,  // 0: browserproxy.v1.ClientMsg.navigate:type_name -> browserproxy.v1.Navigate
	2,  // 1: browserproxy.v1.ClientMsg.click:type_name -> browserproxy.v1.Click
	3,  // 2: browserproxy.v1.ClientMsg.scroll:type_name -> browserproxy.v1.Scroll
	4,  // 3: browserproxy.v1.ClientMsg.key:type_name -> browserproxy.v1.Key
	5,  // 4: browserproxy.v1.ClientMsg.resize:type_name -> browserproxy.v1.Resize
	6,  // 5: browserproxy.v1.ClientMsg.back:type_name -> browserproxy.v1.Back
	7,  // 6: browserproxy.v1.ClientMsg.forward:type_name -> browserproxy.v1.Forward
	9,  // 7: browserproxy.v1.ServerMsg.frame:type_name -> browserproxy.v1.Frame
	10, // 8: browserproxy.v1.ServerMsg.state:type_name -> browserproxy.v1.State
	11, // 9: browserproxy.v1.ServerMsg.error:type_name -> browserproxy.v1.Error
	0,  // 10: browserproxy.v1.Browser.Session:input_type -> browserproxy.v1.ClientMsg
	8,  // 11: browserproxy.v1.Browser.Session:output_type -> browserproxy.v1.ServerMsg
	11, // [11:12] is the sub-list for method output_type
	10, // [10:11] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_proto_browser_proto_init() }
func file_proto_browser_proto_init() {
	if File_proto_browser_proto != nil {
		return
	}
	file_proto_browser_proto_msgTypes[0].OneofWrappers = []any{
		(*ClientMsg_Navigate)(nil),
		(*ClientMsg_Click)(nil),
		(*ClientMsg_Scroll)(nil),
		(*ClientMsg_Key)(nil),
		(*ClientMsg_Resize)(nil),
		(*ClientMsg_Back)(nil),
		(*ClientMsg_Forward)(nil),
	}
	file_proto_browser_proto_msgTypes[8].OneofWrappers = []any{
		(*ServerMsg_Frame)(nil),
		(*ServerMsg_State)(nil),
		(*ServerMsg_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_browser_proto_rawDesc), len(file_proto_browser_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_browser_proto_goTypes,
		DependencyIndexes: file_proto_browser_proto_depIdxs,
		MessageInfos:      file_proto_browser_proto_msgTypes,
	}.Build()
	File_proto_browser_proto = out.File
	file_proto_browser_proto_goTypes = nil
	file_proto_browser_proto_depIdxs = nil
}
